- name: 'Copy login.sh'
  copy:
    src: login.sh
    dest: /opt/login.sh
    owner: root
    group: root
    mode: '0755'

- name: 'Copy login-job.sh'
  copy:
    src: login-job.sh
    dest: /opt/login-job.sh
    owner: root
    group: root
    mode: '0755'

- name: 'Copy gitconfig'
  copy:
    src: gitconfig
    dest: /opt/gitconfig
    owner: root
    group: root
    mode: '0644'

