- name: 'Install Traefik as AuthProxy'
  environment: '{{ params }}'
  shell: |
     set -e
     curl -L "https://github.com/traefik/traefik/releases/download/v3.2.1/traefik_v3.2.1_linux_amd64.tar.gz" -o "/tmp/trafik.tar.gz"
     tar -xvf /tmp/trafik.tar.gz -C /opt/

- name: 'Create group'
  group:
    name: "traefik"
    gid: 2039
    system: yes
    state: present
    
- name: 'Add traefik user'
  user:
    name: "traefik"
    uid: 2040
    group: "traefik"
    system: yes
    state: present

- name: 'Create traefik dir'
  file:
    path: /etc/traefik
    state: directory
    mode: '0755'
    owner: traefik
    group: traefik

- name: 'Create traefik config dir'
  file:
    path: /etc/traefik/config
    state: directory
    mode: '0755'
    owner: traefik
    group: traefik


- name: 'Create traefik log dir'
  file:
    path: /var/log/traefik/
    state: directory
    mode: '0755'
    owner: traefik
    group: traefik

- name: 'Copy traefik'
  copy:
    src: traefik.service
    dest: /etc/systemd/system
    owner: root
    group: root


- name: 'Copy traefik config'
  copy:
    src: traefik.toml
    dest: /etc/traefik/traefik.toml
    owner: root
    group: root

- name: 'Copy traefik file config'
  copy:
    src: config.toml
    dest: /etc/traefik/config/config.toml
    owner: root
    group: root

- name: 'Enable traefik service'
  systemd:
    name: traefik 
    enabled: yes
    state: stopped

- name: 'Install pip deps for traefik user'
  environment: '{{ params }}'
  shell: |
    set -e 
    pip3 install pyjwt requests urllib3 boto3 jinja2
  register: result
  retries: 3
  delay: 10
  until: result is not failed
  become: yes
  become_user: 'traefik'

- name: 'Copy docker auth_service'
  copy:
    src: 'auth_server.py'
    dest: '/opt/auth_server.py'
    mode: '744'

- name: 'Copy docker auth_server'
  copy:
    src: 'auth_server.py'
    dest: '/opt/auth_server.py'
    mode: '744'

- name: 'Copy auth_service'
  copy:
    src: auth_server.service
    dest: /etc/systemd/system
    owner: root
    group: root

- name: 'Enable auth service'
  systemd:
    name: auth_server
    enabled: yes
    state: stopped